name: four_methods_pb
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc:
  protobuf: ^2.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  lints: ^2.0.0
